tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: "NoSchedule"

nodeSelector:
  role: ceph-operator-node

csi:
  provisionerTolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: "NoSchedule"
  pluginTolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: "NoSchedule"

discover:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: "NoSchedule"
