apiVersion: plumber.k8s.pf9.io/v1
kind: HostNetworkTemplate
metadata:
  name: hostconfig-net
  namespace: ${NAMESPACE}
spec:
  ovsConfig:
  - bridgeName: ${OVS_BRIDGE}
    nodeInterface: ${SECONDARY_NIC}
