apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-node-2
  name: vm-node-2
spec:
  dataVolumeTemplates:
  - metadata:
      name: vm-node-2-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: ${STORAGE_CLASS_NAME}
      source:
        http:
          url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-node-2
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
          - disk:
              bus: virtio
            name: cloudinit
        machine:
          type: ""
        resources:
          requests:
            memory: 2G
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: vm-node-2-dv
        name: datavolumevolume
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: winterwonderland
            ssh_pwauth: True
            manage_etc_hosts: true
            chpasswd: { expire: False }
            ssh_authorized_keys:
              - ${PUB_SSH_KEY}
        name: cloudinit
