apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: restrict-development-egress
spec:
  # selector: projectcalico.org/namespace not in  {'kube-system', 'calico-system', 'calico-apiserver'}
  selector: projectcalico.org/namespace in  {'development'}
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
  egress:
    - action: Deny
      destination:
        nets:
          - "8.8.8.8/32"
    - action: Allow
      destination:
        nets:
          - "0.0.0.0/0"
