global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 1m
  repeat_interval: 15m
  receiver: "null"
  routes:
    - match:
        alertname: Watchdog
      receiver: "null"
    - receiver: "prometheus-msteams"

receivers:
  - name: "null"
  - name: prometheus-msteams
    webhook_configs:
      - url: "http://prometheus-msteams:2000/${CONNECTOR_NAME}"
        send_resolved: true
