apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{TEAM}}-team-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - deployments/status
  verbs:
  - create
  - get
  - update
  - watch
  - list
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - get
  - update
  - delete
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - create
  - get
  - update
  - delete
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{TEAM}}-team-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{TEAM}}-team-operator
subjects:
- kind: Group
  name: {{TEAM}}-team
  apiGroup: rbac.authorization.k8s.io
---
